filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

setup.dashboards.enabled: true
setup.kibana:
  host: ${KIBANA_HOSTS}
  ssl.enabled: true
  ssl.certificate_authorities: ["${CA_CERT}"]
  ssl.certificate: ${CA_CERT}
  ssl.certificate: ${KIBANA_SSL_CERT}
  ssl.key: ${KIBANA_SSL_KEY}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}